# Spring properties
spring:
  application:
    name: user-service  # Identify this application
  data:
    mongodb:
      database: users_db  # Database name
      host: localhost
      port: 27017
  main:
    allow-bean-definition-overriding: true

# HTTP Server
server.port: 8087   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

management.endpoints.web.exposure.include: '*'